version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

volumes:
  redis_data:
