version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - api-network

  api:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - api-network

volumes:
  redis_data:

networks:
  api-network:
    driver: bridge
